version: 0.2
phases:
  pre_build:
    commands:
      - curl https://rpm.nodesource.com/setup_6.x |  bash -
      - yum install -y epel-release
      - yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - yum install  -y nodejs, gcc, c++, make
      - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
      - yum install -y yarn
  build:
    commands:
      - yarn pack --filename mytest.tar.gz
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - mytest.tar.gz