version: 0.0
os: linux
files:
  - source: /
    destination: /srv/mynodeapp
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
