version: 0.2
phases:
  build:
    commands:
     - mvn clean install
  post_build:
    commands:
       - mvn package
artifacts:
  files:
        - target/javawebapp.war
        - target/javawebapp/appspec.yml
        - scripts/start-server.sh
        - scripts/stop_server.sh
        - appspec.yml
  discard-paths: yes
