---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'My Pipeline'

Parameters:
  CodeBuildProjectName:
    Description: is used as Customer tag value for all resources
    Type: String
    Default: Customer
    AllowedPattern: ^[A-Za-z0-9]*$
    ConstraintDescription: must contain only alphanumeric characters and numbers.
    MaxLength: 20
    MinLength: 1


Resources:
  AppPipeline:
    Type: AWS::CodePipeline::Pipeline 
    Properties: 
      Name: andrew-pipeline
      RoleArn: arn:aws:iam::162855553133:role/service-role/AWSCodePipelineServiceRole-eu-west-2-andrew_pipeline
      Stages: 
        - 
          Name: javawebapp_source 
          Actions:
            - Name: get_source
              ActionTypeId:
                    Category: Source
                    Owner: AWS
                    Provider: CodeCommit
                    Version: "1"
              Configuration:
                RepositoryName: javawebapp
                BranchName: master
              OutputArtifacts:
                - Name: MavenCode
         
        - 
          Name: CodeBuild 
          Actions: 
            - 
              Name: MavenZipFileExport
              ActionTypeId: 
                Category: Build 
                Owner: AWS 
                Version: "1"
                Provider: CodeBuild 
              RunOrder: 1 
              Configuration: 
                ProjectName: buildjavaapp
                PrimarySource: javawebapp
              InputArtifacts:
                - Name: MavenCode
              OutputArtifacts:
                - Name: MavenZipFile
        - 
          Name: DeployMyApp 
          Actions: 
            - 
              Name: DeployAction
              InputArtifacts: 
                - 
                  Name: MavenZipFile 
              ActionTypeId: 
                Category: Deploy 
                Owner: AWS 
                Version: "1" 
                Provider: CodeDeploy 
              Configuration: 
                ApplicationName: codedeploy_java_app 
                DeploymentGroupName: singe_instance_deployment
              RunOrder: 1 

      ArtifactStore:
        Type: S3
        Location: javawebapp-arvind

      
    
